/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAuthedRouteImport } from './routes/app/_authed'
import { Route as AppAuthedIndexRouteImport } from './routes/app/_authed/index'
import { Route as AppAuthedSearchRouteImport } from './routes/app/_authed/search'
import { Route as AppAuthedTasksIndexRouteImport } from './routes/app/_authed/tasks/index'
import { Route as AppAuthedTasksTaskIdIndexRouteImport } from './routes/app/_authed/tasks/$taskId/index'
import { Route as AppAuthedTasksTaskIdKeywordKeywordIdRouteImport } from './routes/app/_authed/tasks/$taskId/keyword/$keywordId'

const AppRouteImport = createFileRoute('/app')()

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthedRoute = AppAuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthedIndexRoute = AppAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedSearchRoute = AppAuthedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedTasksIndexRoute = AppAuthedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedTasksTaskIdIndexRoute =
  AppAuthedTasksTaskIdIndexRouteImport.update({
    id: '/tasks/$taskId/',
    path: '/tasks/$taskId/',
    getParentRoute: () => AppAuthedRoute,
  } as any)
const AppAuthedTasksTaskIdKeywordKeywordIdRoute =
  AppAuthedTasksTaskIdKeywordKeywordIdRouteImport.update({
    id: '/tasks/$taskId/keyword/$keywordId',
    path: '/tasks/$taskId/keyword/$keywordId',
    getParentRoute: () => AppAuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/app': typeof AppAuthedRouteWithChildren
  '/app/search': typeof AppAuthedSearchRoute
  '/app/': typeof AppAuthedIndexRoute
  '/app/tasks': typeof AppAuthedTasksIndexRoute
  '/app/tasks/$taskId': typeof AppAuthedTasksTaskIdIndexRoute
  '/app/tasks/$taskId/keyword/$keywordId': typeof AppAuthedTasksTaskIdKeywordKeywordIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/app': typeof AppAuthedIndexRoute
  '/app/search': typeof AppAuthedSearchRoute
  '/app/tasks': typeof AppAuthedTasksIndexRoute
  '/app/tasks/$taskId': typeof AppAuthedTasksTaskIdIndexRoute
  '/app/tasks/$taskId/keyword/$keywordId': typeof AppAuthedTasksTaskIdKeywordKeywordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/app': typeof AppRouteWithChildren
  '/app/_authed': typeof AppAuthedRouteWithChildren
  '/app/_authed/search': typeof AppAuthedSearchRoute
  '/app/_authed/': typeof AppAuthedIndexRoute
  '/app/_authed/tasks/': typeof AppAuthedTasksIndexRoute
  '/app/_authed/tasks/$taskId/': typeof AppAuthedTasksTaskIdIndexRoute
  '/app/_authed/tasks/$taskId/keyword/$keywordId': typeof AppAuthedTasksTaskIdKeywordKeywordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/app'
    | '/app/search'
    | '/app/'
    | '/app/tasks'
    | '/app/tasks/$taskId'
    | '/app/tasks/$taskId/keyword/$keywordId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/app'
    | '/app/search'
    | '/app/tasks'
    | '/app/tasks/$taskId'
    | '/app/tasks/$taskId/keyword/$keywordId'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/app'
    | '/app/_authed'
    | '/app/_authed/search'
    | '/app/_authed/'
    | '/app/_authed/tasks/'
    | '/app/_authed/tasks/$taskId/'
    | '/app/_authed/tasks/$taskId/keyword/$keywordId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authed': {
      id: '/app/_authed'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/_authed/': {
      id: '/app/_authed/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAuthedIndexRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/search': {
      id: '/app/_authed/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppAuthedSearchRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/tasks/': {
      id: '/app/_authed/tasks/'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppAuthedTasksIndexRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/tasks/$taskId/': {
      id: '/app/_authed/tasks/$taskId/'
      path: '/tasks/$taskId'
      fullPath: '/app/tasks/$taskId'
      preLoaderRoute: typeof AppAuthedTasksTaskIdIndexRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/tasks/$taskId/keyword/$keywordId': {
      id: '/app/_authed/tasks/$taskId/keyword/$keywordId'
      path: '/tasks/$taskId/keyword/$keywordId'
      fullPath: '/app/tasks/$taskId/keyword/$keywordId'
      preLoaderRoute: typeof AppAuthedTasksTaskIdKeywordKeywordIdRouteImport
      parentRoute: typeof AppAuthedRoute
    }
  }
}

interface AppAuthedRouteChildren {
  AppAuthedSearchRoute: typeof AppAuthedSearchRoute
  AppAuthedIndexRoute: typeof AppAuthedIndexRoute
  AppAuthedTasksIndexRoute: typeof AppAuthedTasksIndexRoute
  AppAuthedTasksTaskIdIndexRoute: typeof AppAuthedTasksTaskIdIndexRoute
  AppAuthedTasksTaskIdKeywordKeywordIdRoute: typeof AppAuthedTasksTaskIdKeywordKeywordIdRoute
}

const AppAuthedRouteChildren: AppAuthedRouteChildren = {
  AppAuthedSearchRoute: AppAuthedSearchRoute,
  AppAuthedIndexRoute: AppAuthedIndexRoute,
  AppAuthedTasksIndexRoute: AppAuthedTasksIndexRoute,
  AppAuthedTasksTaskIdIndexRoute: AppAuthedTasksTaskIdIndexRoute,
  AppAuthedTasksTaskIdKeywordKeywordIdRoute:
    AppAuthedTasksTaskIdKeywordKeywordIdRoute,
}

const AppAuthedRouteWithChildren = AppAuthedRoute._addFileChildren(
  AppAuthedRouteChildren,
)

interface AppRouteChildren {
  AppAuthedRoute: typeof AppAuthedRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthedRoute: AppAuthedRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
